---
# sub tasks file for yh-run-clean
#
# Add Service: yh-run-clean 
#


# ####################################
# Service - Dataset/bucket
# ####################################
- block:

  # 生成启动脚本
  - name: gen-unit-script
    template: src="yh-run-clean.sh.j2" dest="{{ yhrc_service_ctl_script }}" mode=0755


# ####################################
# Service - Scripts
# ####################################
- block:

  - name: gen-unit-svc
    template: src="yh-run-clean.service.j2" dest="/lib/systemd/system/{{ yhrc_service_name }}.service" mode=0644

  - name: reg-svc
    systemd: name="{{ yhrc_service_name }}" enabled=yes
  
  # 服务只在系统启动时启用，清理pid, lock文件.

  become: true
  become_user: root


# ####################################
# Service - Post Process
# ####################################
