---
# tasks file for yh-run-clean


# Configure - Service - Add
- block:
  - include_tasks: add-svc.yml
  become: true
  become_user: "{{ xdc_user }}"
  when: sub_cmd == "config" or sub_cmd == "add-svc"


# Configure - Service - Remove
- block:
  - include_tasks: rm-svc.yml
  become: true
  become_user: "{{ xdc_user }}"
  when: sub_cmd == "rm-svc"
