---
# sub tasks file for yh-mongo
#
# Add Service: mongod 
#


# ####################################
# Service - Dataset/bucket
# ####################################
- block:

  # 配置、数据区
  - name: verify-unit-dir
    file: state=directory recurse=yes path="{{item}}"
    with_items:
      - "{{ mongod_unit_home }}"
      - "{{ xdc_prefix }}/bin"
      - "{{ xdc_prefix }}/etc"
      - "{{ xdc_prefix }}/var/run"
      - "{{ xdc_prefix }}/data/{{ mongod_unit_name }}"
      - "{{ xdc_prefix }}/log/{{ mongod_unit_name }}"

  # 生成启动脚本
  - name: gen-unit-script
    template: src="mongod.sh.j2" dest="{{ xdc_prefix }}/bin/{{ mongod_unit_name }}.sh" mode=0755

  # 生成配置文件
  - name: gen-unit-conf
    template: src="mongod.conf.j2" dest="{{ xdc_prefix }}/etc/{{ mongod_unit_name }}.conf" mode=0644

  # 数据聚合区
  - name: verify-unit-link-dir
    file: state=link src="{{item.src}}" dest="{{item.dest}}" force=yes
    with_items:
      - { src: "../../bin/{{ mongod_unit_name }}.sh", dest: "{{ mongod_service_ctl_script }}" }
      - { src: "../../etc/{{ mongod_unit_name }}.conf", dest: "{{ mongod_service_conf_file }}" }
      - { src: "../../data/{{ mongod_unit_name }}", dest: "{{ mongod_unit_home }}/data" }
      - { src: "../../log/{{ mongod_unit_name }}", dest: "{{ mongod_unit_home }}/log" }


# ####################################
# Service - Scripts
# ####################################
- block:

  - name: gen-unit-svc
    template: src="mongod.service.j2" dest="/lib/systemd/system/{{ mongod_service_name }}.service" mode=0644

  - name: reg-svc
    systemd: name="{{ mongod_service_name }}" enabled=yes

  - name: start-svc
    systemd: name="{{ mongod_service_name }}" state=started

  become: true
  become_user: root


# ####################################
# Service - Post Process
# ####################################
- block:

  - name: copy-repset-js-2-agent
    template: src="repset.js.j2" dest="/tmp/ansible_mongod_repset.js"

  - name: config-repset
    shell: "mongo --port {{ mongod_port }} admin < /tmp/ansible_mongod_repset.js"
    environment:
      PATH: "{{ mongo_global_link_home }}/bin:{{ ansible_env.PATH }}"
  
  - name: rm-repset-tmp-file
    file: state=absent path="/tmp/ansible_mongod_repset.js"

  when: mongod_conf_replSet and mongod_conf_replSet_exec
  run_once: true
