---
# sub tasks for yh-mongo

# 读取特定配置
- name: load-spec-version
  include_vars: "mongo-xxx.yml"
  when: mongo_version == 'xxx'


# 目录准备
- name: verify-stub-dir
  file: state=directory recurse=yes path="{{ software_stub_dir_path }}"

- name: verify-opt-dir
  file: state=directory recurse=yes path="{{ software_opt_dir_path }}"


# 下载pkg
- block:

  - name: verify-mongo-pkg-exist | {{ mongo_local_pkg_path }}
    stat: path="{{ mongo_local_pkg_path }}" get_checksum=true checksum_algorithm=md5
    register: mongo_pkg_stat

  - name: download-mongo-pkg
    get_url: 
      url: "{{ mongo_download_url }}"
      dest: "{{ mongo_local_pkg_path }}"
      validate_certs: no
      headers: "{{ mongo_download_headers }}"
    when: not mongo_pkg_stat.stat.exists or mongo_pkg_stat.stat.checksum != (mongo_pkg_md5)

  tags: mongo download


# 绿色解压
- name: unarchive-mongo-pkg to {{ mongo_install_home }}
  unarchive:
    src: "{{ mongo_local_pkg_path }}"
    dest: "{{ software_opt_dir_path }}"
    remote_src: yes
    creates: "{{ mongo_install_home }}"


# 共享给所有用户
- block:

  - name: verify-global-kits-home {{ global_kits_home }}
    file: state=directory recurse=yes path="{{ global_kits_home }}" owner="{{ software_install_user }}" group="{{ software_install_group }}"
    become: true
    become_user: root

  - name: share-to-global-kits to {{ global_kits_home }}
    file: state=link src="{{ mongo_install_home }}" dest="{{ mongo_global_link_home }}" force=yes

