---
# tasks file for yh-mongo


# 初始化，
#   1. 自动获取计算配置
#   2. 除非执行uninstall, 否则自动执行install
- include_tasks: init.yml


# 配置 - 服务 - 添加
- block:
  - include_tasks: add-svc.yml
  become: true
  become_user: "{{ xdc_user }}"
  when: sub_cmd == "config" or sub_cmd == "add-svc"


# 配置 - 服务 - 移除
- block:
  - include_tasks: rm-svc.yml
  become: true
  become_user: "{{ xdc_user }}"
  when: sub_cmd == "rm-svc"


# 配置 - mongo使用者
- block:
  - include_tasks: config.yml
  become: true
  become_user: "{{ end_user }}"
  when: end_user != "" and (sub_cmd == "config")

