---
# tasks file for yh-ssh-key


# 生成、部署
- block:

  - name: gen-ssh-key
    shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
    args:
      creates: ~/.ssh/id_rsa

  - name: fetch-ssh-key
    shell: cat ~/.ssh/id_rsa.pub
    register: ssh_keys

  - name: deploy-keys-to-all-servers
    authorized_key:
      user: "{{ end_user }}"
      key: "{{ hostvars[item].ssh_keys.stdout }}"
      state: present
    with_items:
      - "{{ play_hosts }}"

  become: yes
  become_user: "{{ end_user }}"
  # when: False


# 调试
- block:

  - name: show-server
    shell: echo {{item}}
    with_items:
      - "{{ play_hosts }}"

  - name: show-info
    shell: pwd && id && whoami
    register: result

  - debug: var=result.stdout

  become: yes
  become_user: "{{ end_user }}"
  when: debug_mode
