---
# defaults file for yh-nodejs


# ####################################
# User Config
# ####################################
end_user: "foobar"    # nodejs user
sub_cmd: "config"     # config
main_version: 8       # nodejs main version


# ####################################
# Install Config
# ####################################

# Install Dir Config
global_kits_home: "/usr/xhub"
software_install_home: "/home/linuxbrew"
software_stub_dir_path: "{{ software_install_home }}/stub"
software_opt_dir_path: "{{ software_install_home }}/opt"

# Resource Version Config
nodejs_ver: "8.16"
nodejs_version: "8.16.0"
nodejs_pkg_md5: "caabf1838fba99b1d228dfa66c38254f"
nodejs_pkg_name: "node-v{{ nodejs_version }}-linux-x64.tar.gz"
nodejs_install_dir_name: "node-v{{ nodejs_version }}-linux-x64"
nodejs_download_url: "https://npm.taobao.org/mirrors/node/v{{ nodejs_version }}/{{ nodejs_pkg_name }}"
nodejs_download_headers: {}
nodejs_local_pkg_path: "{{ software_stub_dir_path }}/{{ nodejs_pkg_name }}"
nodejs_install_home: "{{ software_opt_dir_path }}/{{ nodejs_install_dir_name }}"
nodejs_global_link_home: "{{ global_kits_home }}/nodejs-{{ nodejs_ver }}"


# ####################################
# Auto Computed Config
# ####################################
software_install_user: ""     # Green-Install-User
software_install_group: ""    # Green-Install-Group
