---
# sub task file for yh-nodejs
#
# 安装nodejs扩展
#


# 安装 cnpm
- name: install-cnpm
  command: "{{ nodejs_global_link_home }}/bin/npm install -g cnpm --registry https://registry.npm.taobao.org"
  args:
    creates: "{{ nodejs_global_link_home }}/bin/cnpm"
  environment:
    PATH: "{{ nodejs_global_link_home }}/bin:{{ ansible_env.PATH }}"

# 安装xx
