---
# sub tasks for yh-nodejs

# 读取特定配置
- name: load-spec-version
  include_vars: "nodejs-xxx.yml"
  when: nodejs_version == 'xxx'


# 目录准备
- name: verify-stub-dir
  file: state=directory recurse=yes path="{{ software_stub_dir_path }}"

- name: verify-opt-dir
  file: state=directory recurse=yes path="{{ software_opt_dir_path }}"


# 下载pkg
- block:

  - name: verify-nodejs-pkg-exist | {{ nodejs_local_pkg_path }}
    stat: path="{{ nodejs_local_pkg_path }}" get_checksum=true checksum_algorithm=md5
    register: nodejs_pkg_stat

  - name: download-nodejs-pkg
    get_url: 
      url: "{{ nodejs_download_url }}"
      dest: "{{ nodejs_local_pkg_path }}"
      validate_certs: no
      headers: "{{ nodejs_download_headers }}"
    when: not nodejs_pkg_stat.stat.exists or nodejs_pkg_stat.stat.checksum != (nodejs_pkg_md5)

  tags: nodejs download


# 绿色解压
- name: unarchive-nodejs-pkg to {{ nodejs_install_home }}
  unarchive:
    src: "{{ nodejs_local_pkg_path }}"
    dest: "{{ software_opt_dir_path }}"
    remote_src: yes
    creates: "{{ nodejs_install_home }}"


# 共享给所有用户
- block:

  - name: verify-global-kits-home {{ global_kits_home }}
    file: state=directory recurse=yes path="{{ global_kits_home }}" owner="{{ software_install_user }}" group="{{ software_install_group }}"
    become: true
    become_user: root

  - name: share-to-global-kits to {{ global_kits_home }}
    file: state=link src="{{ nodejs_install_home }}" dest="{{ nodejs_global_link_home }}" force=yes

