---
# tasks file for yh-nodejs


# 初始化，
#   1. 自动获取计算配置
#   2. 除非执行uninstall, 否则自动执行install
- include_tasks: init.yml


# 配置
- block:
  - include_tasks: config.yml
  become: true
  become_user: "{{ end_user }}"
  when: end_user != "" and (sub_cmd == "config")
