---
# sub tasks file for yh-user


# 确保用户存在
- block:
  - name: verify-yh-group
    group: name="{{ yh_group }}" gid={{ yh_gid }}
  - name: verify-yh-user
    user: name="{{ yh_user }}" uid={{ yh_uid }} group="{{ yh_group }}" home="{{ yh_home }}" shell="/bin/bash"
  tags: verify-yh-group-user


# ~/.ssh 目录配置及设置正确权限，方便ssh打通
- block:
  - name: verify-ssh-dir
    file: path="{{ yh_home }}/.ssh/" state=directory owner="{{ yh_user }}" group="{{ yh_group }}" mode=0700
  tags: sync-home-ssh-config


# 立即子目录
- block:
  - name: Init yh-1st-sub-dir
    file: state=directory recurse=yes path="{{ item }}" owner={{ yh_user }} group={{ yh_group }}
    with_items:
      - "{{ yh_bin_path }}"
      - "{{ yh_etc_path }}"
      - "{{ yh_data_path }}"
      - "{{ yh_stub_path }}"
      - "{{ yh_backup_path }}"
  tags: yh-1st-sub-dir


# 运行时目录
- block:

  - name: Init yh-var-log-runtime-dir
    file: state=directory recurse=yes path="{{ item }}" owner={{ yh_user }} group={{ yh_group }}
    with_items:
      - "{{ var_log_hub }}"
      - "{{ var_lib_hub }}"
      - "{{ yh_var_path }}"
      - "{{ yh_run_path }}"   # 因为run目录是内存，所以就不映射咯.

  - name: link-user-var-2-system-var
    file: state=link src="{{ item.src }}" dest="{{ item.dest }}" owner={{ yh_user }} group={{ yh_group }}
    with_items:
      - { src: "{{ var_log_hub }}", dest: "{{ yh_log_path }}" }
      - { src: "{{ var_lib_hub }}", dest: "{{ yh_runtime_path }}" }

  - name: reg-sudoers
    template: src="99-yh-user.j2" dest="{{ global_sudoers_ext_file }}"
    when: can_sudo

  tags: yh-var-log-runtime-dir
