---
# sub tasks for yh-os-init
#
# Install for Redhat/CentOS
#


# 安装 Redhat/CentOS 必备工具集
- block:
  - name: upgrade-all
    yum: name="*" state=latest
  - name: install-dev-env
    yum: name="@Development tools" state=present
  - name: install-com-tools-libs
    yum:
      name: [ "vim", "tree", "screen", "ruby", "net-tools", "bind-utils", "iputils", "telnet", "lsof", "numactl" ]
  when: ansible_os_family == "RedHat"
  tags: install-com-tools-libs


# 校准时间 ntp
- block:
  - name: yum-install-ntp
    yum: name=ntp state=installed
  # - name: sync-time-with-server
  #   shell: ntpupdate 0.asia.pool.ntp.org && hwclock --systohc
  #   ignore_errors: true
  - name: change-ntp-server
    template: src=ntp.conf.j2 dest=/etc/ntp.conf backup=yes
    notify: restart ntpd
  tags: ntp time


# ulimit 文件句柄
- name: Change nofile limits.
  lineinfile: 
    path: /etc/security/limits.conf
    line: "{{ item }}"
  with_items:
    - '* - nofile 165535'
    - '* soft nofile 165535'
    - '* hard nofile 165535'
  tags: ulimit


# 安全
- name: disable-selinux
  replace:
    path: "/etc/selinux/config"
    regexp: ^SELINUX=enforcing
    replace: SELINUX=disabled
  tags: secruity selinux


# sysctl
- block:
  - name: Set vm.overcommit_memory to 1 in /etc/sysctl.conf.
    sysctl:
      name: vm.overcommit_memory
      value: 1
      state: present
    tags: sysctl vm overcommit_memory

  - name: Set vm.swappiness to 1 in /etc/sysctl.conf.
    sysctl: name="vm.swappiness" value=1 state=present
    tags: sysctl vm swappiness
